GET http://localhost:5000/users

###
GET http://localhost:5000/users/5

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Jhon Doe",
    "email": "jhon@gmail.com",
    "gender": "Male"
}

###
PATCH  http://localhost:5000/users/3
Content-Type: application/json

{
    "name": "Jhon Doe 3",
    "email": "jhon@gmail.com",
    "gender": "Male"
}

###
DELETE http://localhost:5000/users/4
